import 'package:flutter/material.dart';

class AppInkWell extends InkWell {
  const AppInkWell({
    super.key,
    super.child,
    super.onTap,
    super.onDoubleTap,
    super.onLongPress,
    super.onTapDown,
    super.onTapUp,
    super.onTapCancel,
    super.onSecondaryTap,
    super.onSecondaryTapUp,
    super.onSecondaryTapDown,
    super.onSecondaryTapCancel,
    super.onHighlightChanged,
    super.onHover,
    super.mouseCursor,
    super.focusColor = Colors.transparent,
    super.hoverColor = Colors.transparent,
    super.highlightColor = Colors.transparent,
    super.splashColor = Colors.transparent,
    super.overlayColor,
    super.splashFactory,
    super.radius,
    super.borderRadius,
    super.customBorder,
    super.excludeFromSemantics,
    super.focusNode,
    super.canRequestFocus,
    super.onFocusChange,
    super.autofocus,
    super.statesController,
  });
}
